site_name: Documentación con mkdocs y GitHub
site_url: https://osalinaseduca.github.io/Documentacion_Proyecto/
docs_dir: 'docs_src'
site_dir: 'docs'
nav:
  - home: index.md
  - Manual de Usuario: Manual_de_Usuario.md
  - Guia de Referencia: Guia_de_Referencia.md
  - Guia de instalación: Guia_de_Instalacion.md
  - Descargas:
      - Manual de usuario PDF:  Manual_de_Usuario/Manual_de_Usuario.pdf
      - Guia_de_Referencia PDF: Guia_de_Referencia/Guia_de_Referencia.pdf
      - Guia_de_Instalacion PDF: Guia_de_Instalacion/Guia_de_Instalacion.pdf
theme:  readthedocs

plugins:
  - search
  - pdf-export:
      enable_if_env: ENABLE_PDF_EXPORT
      media_type: print


output_path: pdf/Documentacion_proyecto.pdf



