site_name: Documentación con mkdocs y GitHub
site_url: https://osalinaseduca.github.io/Documentacion_Proyecto/
docs_dir: 'docs_src'
site_dir: 'docs'
nav:
  - 1: Manual_de_Usuario.md
  - 2: Guia_de_Referencia.md
  - 3: Guia_de_Instalacion.md
  - Descarga en pdf: PDF.md


plugins:
  - search
  - pdf-export
  - with-pdf:
      author: Ferran Cunyat Pellicer
      copyright: CC0O 1.0 Universal
      cover: true
      back_cover: false
      cover_title: Holamundo! con PySide6
      cover_subtitle: Desarrollo interfaces - 2% DAM - Ed. McGrawHill
      toc_title: Índice
      toc_level: 2
      ordered_chapter_level: 2
    
      # Excluir algunas páginas si es necesario
      # exclude_pages:
      #   - 'bugs/'
      #   - 'appendix/contribute/'
      # Convertir iframes en imágenes si es necesario
      # convert_iframe:
      #   - src: IFRAME_SRC
      #     img: POSTER_IMAGE_URL
      #     text: ALTERNATE_TEXT
      #   - src:...
      # Configurar un nivel de columnas
      # two_columns_level: 3

output_path: pdf/Documentacion_proyecto.pdf



