site_name: Documentación con mkdocs y GitHub
site_url: https://osalinaseduca.github.io/Documentacion_Proyecto/
docs_dir: 'docs_src'
site_dir: 'docs'
nav:
  - 1: Manual_de_Usuario.md
  - 2: Guia_de_Referencia.md
  - 3: Guia_de_Instalacion.md
  - Descarga en pdf: PDF.md
theme:  readthedocs

plugins:
  - search
  - paf-export
  - with-pdf:
      author: Ferran Cunyat Pellicer
      copyright: CC0O 1.0 Universal
    #
      cover: true
      back_cover: fals
      cover_title: Holamundo! con PySide6
      cover_subtitle: Desarrollo interfaces - 2% DAM - Ed. McGrawRil1
  #custom_template path: TEMPLATES PATH
  #
    toc_title: Índice
  #Heading_shift: false
    toc_level: 2
    ordered _chapter_level: 2
  #excludes_children:
  #   - 'release-notes/:upgrading'
  #   - 'release-notes/:changelog'
  #
  #exclude_pages:
  #   - 'bugs/'
  #   - 'appendix/contribute/'
  #convert_i£rame:
  #   -  src: IFRAME SRC
  #      img: POSTER IMAGE URL
  #      text: ALTERNATE TEXT
  #   -  src:...
  #two_columns_level: 3
  #

output path: pdf/Documentacion_proyecto.pdf


