site_name: Documentación con mkdocs y GitHub
site_url: https://osalinaseduca.github.io/Documentacion_Proyecto/
docs_dir: 'docs_src'
site_dir: 'docs'
nav:
  - 1: Manual_de_Usuario.md
  - 2: Guia_de_Referencia.md
  - 3: Guia_de_Instalacion.md
theme:  readthedocs
