site_name: Documentación con mkdocs y GitHub
site_url: https://osalinaseduca.github.io/Documentacion_Proyecto/
docs_dir: 'docs_src'
site_dir: 'docs'
nav:
  - 1: Manual_de_Usuario.md
  - 2: Guia_de_Referencia.md
  - 3: Guia_de_Instalacion.md
  - Descargas:
      - Manual de usuario PDF: pdf/Manual_de_Usuario.pdf
      - Guia de Referencia PDF: pdf/Guia_de_Referencia.pdf
      - Guia de Instalacion PDF: pdf/Guia_de_Instalacion.pdf
theme:  readthedocs

plugins:
  - search
  - pdf-export:
      enable_if_env: ENABLE_PDF_EXPORT
      media_type: print


output_path: pdf/Documentacion_proyecto.pdf



